// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyQr1G3bvpcGHf26fQ9Lc6H-QPgGfyaJs',
    appId: '1:206697994054:web:037f6bbb5f69c7494f7747',
    messagingSenderId: '206697994054',
    projectId: 'flutter-lab-3-b2c1d',
    authDomain: 'flutter-lab-3-b2c1d.firebaseapp.com',
    databaseURL: 'https://flutter-lab-3-b2c1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-lab-3-b2c1d.firebasestorage.app',
    measurementId: 'G-L343GCKLBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB76OTwyWcGUnTS_en59Dci8XsT_3eD86o',
    appId: '1:206697994054:android:e1d7d716ea9fb0354f7747',
    messagingSenderId: '206697994054',
    projectId: 'flutter-lab-3-b2c1d',
    databaseURL: 'https://flutter-lab-3-b2c1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-lab-3-b2c1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKgcOy50JaeQFrl5YlIYR2kcHDgs6iCY',
    appId: '1:206697994054:ios:7becf73c6c751b544f7747',
    messagingSenderId: '206697994054',
    projectId: 'flutter-lab-3-b2c1d',
    databaseURL: 'https://flutter-lab-3-b2c1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-lab-3-b2c1d.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKgcOy50JaeQFrl5YlIYR2kcHDgs6iCY',
    appId: '1:206697994054:ios:7becf73c6c751b544f7747',
    messagingSenderId: '206697994054',
    projectId: 'flutter-lab-3-b2c1d',
    databaseURL: 'https://flutter-lab-3-b2c1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-lab-3-b2c1d.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyQr1G3bvpcGHf26fQ9Lc6H-QPgGfyaJs',
    appId: '1:206697994054:web:6f996cd941cb12764f7747',
    messagingSenderId: '206697994054',
    projectId: 'flutter-lab-3-b2c1d',
    authDomain: 'flutter-lab-3-b2c1d.firebaseapp.com',
    databaseURL: 'https://flutter-lab-3-b2c1d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-lab-3-b2c1d.firebasestorage.app',
    measurementId: 'G-WE4XR2RM89',
  );

}